=== Akhila1019/netcentric-project/XML/company_1.xsd
<xs:schema elementFormDefault="qualified" targetNamespace="http://example.org/company" 
xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Company">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="CompanyId" type="xs:string"/>
                <xs:element name="CompanyName" type="xs:string"/>
                <xs:element name="CompanyInfo" type="xs:string"/>
                <xs:element name="CompanyAddress" type="xs:string"/>
                <xs:element name="Work" type="xs:string"/>
                <xs:element name="No_of_workers" type="xs:string"/>
                <xs:element name="Company_Salary_per_day" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Akhila1019/netcentric-project/XML/company_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Company xmlns="http://example.org/company" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://example.org/company company_1.xsd">
    <CompanyId></CompanyId>
    <CompanyName></CompanyName>
    <CompanyInfo></CompanyInfo>
    <CompanyAddress></CompanyAddress>
    <Work></Work>
    <No_of_workers></No_of_workers>
    <Company_Salary_per_day></Company_Salary_per_day>
</Company>
