=== Akhila1019/netcentric-project/XML/worker_1.xsd
<xs:schema elementFormDefault="qualified" targetNamespace="http://example.org/worker" 
xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Worker">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="WorkerId" type="xs:string"/>
                <xs:element name="WorkerName" type="xs:string"/>
                <xs:element name="WorkerAge" type="xs:string"/>
                <xs:element name="WorkerAddress" type="xs:string"/>
                <xs:element name="WorkerGender" type="xs:string"/>
                <xs:element name="WorkerPhoneNo" type="xs:string"/>
                <xs:element name="Occupation" type="xs:string"/>
                <xs:element name="Experience" type="xs:string"/>
                <xs:element name="Salary_per_day" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Akhila1019/netcentric-project/XML/worker_1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Worker xmlns="http://example.org/worker" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://example.org/worker worker_1.xsd">
    <WorkerId></WorkerId>
    <WorkerName></WorkerName>
    <WorkerAge></WorkerAge>
    <WorkerAddress></WorkerAddress>
    <WorkerGender></WorkerGender>
    <WorkerPhoneNo></WorkerPhoneNo>
    <Occupation></Occupation>
    <Experience></Experience>
    <Salary_per_day></Salary_per_day>
</Worker>
