=== Akhila1019/netcentric-project/XML/worker_0.dtd
<!ELEMENT Worker (WorkerName,WorkerAge,WorkerAddress,WorkerGender,WorkerPhoneNo,Occupation,Experience,Salary_per_day)>
<!ATTLIST Worker WorkerId ID #REQUIRED>
<!ELEMENT WorkerName (#PCDATA)>
<!ELEMENT WorkerAge (#PCDATA)>
<!ELEMENT WorkerAddress (#PCDATA)>
<!ELEMENT WorkerGender (#PCDATA)>
<!ELEMENT WorkerPhoneNo (#PCDATA)>
<!ELEMENT Occupation (#PCDATA)>
<!ELEMENT Experience (#PCDATA)>
<!ELEMENT Salary_per_day (#PCDATA)>

=== Akhila1019/netcentric-project/XML/worker_0.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Worker SYSTEM "worker_0.dtd">
<Worker WorkerId="i-1">
    <WorkerName></WorkerName>
    <WorkerAge></WorkerAge>
    <WorkerAddress></WorkerAddress>
    <WorkerGender></WorkerGender>
    <WorkerPhoneNo></WorkerPhoneNo>
    <Occupation></Occupation>
    <Experience></Experience>
    <Salary_per_day></Salary_per_day>
</Worker>
